### ISSUE TITLE
Search component is not working

### ISSUE THREAD

**Issue by archanaserver** [FNNDSC/ChRIS_store_ui#145]
When I try to `search` any plugins by it's name, it's not showing us relevant result. Also, if I search for anything random which not present in our plugin list, it should show something like **Plugin not found**

One more things we can do here is to add search suggestion with autocomplete component, when we start typing any plugin name. What's your suggestion @mairin @jennydaman?

Example: in the below screenshot you can see in the url i have tried to search `pl-pfdo_mgz2img` plugin and click `enter` but it's not showing us relevant result.

![Screenshot 2021-04-13 at 6 04 44 PM](https://user-images.githubusercontent.com/32739028/114553995-dc8fea00-9c83-11eb-8b5e-05553efabf74.png)

**Comment by mairin** [comment]
Hi @archanaserver - the broken search is a known issue that @sonylomo fixed in https://github.com/FNNDSC/ChRIS_store_ui/pull/134 - that was merged 2 days ago. Have you updated your local copy yet? You might not be running the latest version of the code.

A type-ahead / autocomplete component would be great though if not already present. Can you update your checkout and verify that the new search fix works, and see if there is an autocomplete? If there is no autocomplete in the latest version, let's convert this ticket to be an enhancement to add autocomplete search. Does that make sense?

**Comment by jennydaman** [comment]
related issue: forward-port #134 to the `pf4` branch @DivyanshiSingh and I have been working on.
https://github.com/FNNDSC/ChRIS_store_ui/issues/146
