### ISSUE TITLE
Fuzzy queries must be possible for plugin's name.

### ISSUE THREAD

**Issue by jdtzmn** [FNNDSC/ChRIS_store_ui#7]
See FNNDSC/ChRIS_store#2.

**Comment by gagansk** [comment]
Can the issue be described more? Is it Fuzzy queries must be supported for plugin search or Fuzzy queries must be used to suggest the plugin name dynamically based on the availability during creation?

**Comment by mairin** [comment]
I think this is for searching for plugins. I would say the first task here would be to get the ChRIS store up and running, add a bunch of new plugins, and then test out the search to see how exact queries must be.

**Comment by sonylomo** [comment]
Hey @mairin, I'd like to work on this 😁.

**Comment by sonylomo** [comment]
Is it ok to use a library like Fuse.js to implement fuzzy search?

**Comment by jennydaman** [comment]
Fuzzy search is better implemented server-side (faster).

The back-end supports partial matching of queries, for example `https://chrisstore.co/api/v1/plugins/search?name=pl-fetal` returns `pl-fetal-brain-mask` and `pl-fetal-brain-assessment`. More advanced fuzzy querying, such as typo correction, might be out of scope — especially because names might use esoteric abbreviations such as `pl-pfdo_med2img`.

I suppose the real issue for now is to correctly implement search against the `/api/v1/plugins/search?name=%s` endpoint.

Another related goal would be to implement [OpenSearch](https://developer.mozilla.org/en-US/docs/Web/OpenSearch). I've created a separate issue for this https://github.com/FNNDSC/ChRIS_store_ui/issues/121
